/*
  Warnings:

  - Added the required column `state` to the `ExamAttempt` table without a default value. This is not possible if the table is not empty.

*/
-- CreateEnum
CREATE TYPE "States" AS ENUM ('ANDHRAPRADESH', 'ARUNACHALPRADESH', 'ASSAM', 'BIHAR', 'CHHATTISGARH', 'GOA', 'GUJARAT', 'HARYANA', 'HIMACHALPRADESH', 'JHARKHAND', 'KARNATAKA', 'KERALA', 'MADHYAPRADESH', 'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM', 'NAGALAND', 'ODISHA', 'PUNJAB', 'RAJASTHAN', 'SIKKIM', 'TAMILNADU', 'TELANGANA', 'TRIPURA', 'UTTARPRADESH', 'UTTARAKHAND', 'WESTBENGAL', 'ANDAMAN_AND_NICOBAR_ISLANDS', 'CHANDIGARH', 'DADRA_AND_NAGAR_HAVELI_AND_DAMAN_AND_DIU', 'DELHI', 'LAKSHADWEEP', 'PUDUCHERRY', 'LADAKH', 'JAMMU_AND_KASHMIR');

-- AlterTable
ALTER TABLE "ExamAttempt" ADD COLUMN     "state" "States" NOT NULL;
